FROM ubuntu:18.04

ENV LC_ALL="C.UTF-8"
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive
ADD sources.list /etc/apt/
RUN apt-get update
RUN apt install -y tzdata \
    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata
RUN apt-get install -y net-tools build-essential
RUN rm -rf /var/lib/apt/lists/*